# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a42ad58daaf461cca044e609a27c052c8268917bf3906c94b74bb26132ba3d2b968ea8cf2230ccdb5250d419b9f756d46858fb0838947310ed950ecc7cae6dae

test:
  secret_key_base: 53a25b0adbbaa1779f6697cdb44587f55206b615a22c63c5c16285b9857f3daa0c05fb50c9d605efe3e405a4bf2dee12663bf247d2d50574036ce9fecd37e88a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
